"""Initial migration for Song model

Revision ID: a9b7417be696
Revises: 
Create Date: 2025-09-02 12:27:01.363128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b7417be696'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('lyrics', sa.Text(), nullable=False),
    sa.Column('style', sa.String(length=100), nullable=False),
    sa.Column('mood', sa.String(length=100), nullable=False),
    sa.Column('theme', sa.String(length=100), nullable=False),
    sa.Column('artist_name', sa.String(length=100), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('suno_url', sa.Text(), nullable=True),
    sa.Column('cloudinary_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='songstatus'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    # ### end Alembic commands ###
